---
- hosts: all
  become: yes

  pre_tasks:
    - name: Install docker-compose
      yum:
        name: docker-compose
        state: present
    - name: Création du groupe www-user
      group:
        name: www-data
        state: present
    - name: Création du user www-data
      user: 
        name: www-data
        group: www-data

  roles:
    - role: dirane-wordpress
      vars:
        system_user: vagrant  
